### ISSUE TITLE
Календарь собеседований

### ISSUE THREAD

**Issue by tsepakme** [powerckbestest/job-search-tracker-app#11]
Добавить календарь с отображением прошедших и предстоящих собеседований с отображением по суткам, неделям, месяцам
Как например в teams или calendar
<img width="713" alt="Screenshot 2024-11-14 at 23 46 51" src="https://github.com/user-attachments/assets/382e7c00-b3ae-4050-8990-7545ac0493f5">

**Comment by ruimage** [comment]
@tsepakme нужна синхронизация с google календарем или достаточно виджета?

**Comment by tsepakme** [comment]
Думаю на первое время будет достаточно простого виджета, чтоб пользователи могли видеть какие встречи будут

> @tsepakme нужна синхронизация с google календарем или достаточно виджета?
