### ISSUE TITLE
Баг отмены редактирования

### ISSUE THREAD

**Issue by tsepakme** [powerckbestest/job-search-tracker-app#3]
При редактировании карточки работодателя нельзя отменить действие, при нажатии на кнопку отмены ничего не происходит.
<img width="879" alt="Screenshot 2024-11-14 at 20 05 42" src="https://github.com/user-attachments/assets/84a84bf0-eac7-4e35-abd7-16e2d4fdbd9a">

**Comment by powerckbestest** [comment]
спасибо за фидбек! Пофиксим!
